trigger:
- master

pool:
  name: ven-pool

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: TomcatDeployment@1
  inputs:
    TomcatUrl: '$(url)'
    Username: '$(username)'
    Password: '$(pass)'
    Warfile: 'target/myweb-8.7.3.war'
    Context: '/our-app'
    ServerVersion: '7OrAbove'
